spring:
   cloud:
      stream:
         default-binder: kafka
         kafka:
            binder:
               brokers:
               - kafka-server:9092
         bindings:
            input:
               binder: kafka
               destination: deleteStdRecsTopic
               content-type: text/plain
               group: student-fees-group
            output:
               binder: kafka
               destination: studentUpdate
               group: fees-paid-group
               content-type: application/json
   application:
      name: fees-service
   datasource:
      url: jdbc:mysql://mysql-server:3306/school_fees?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: rootpw
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
server:
   port: 8084
eureka:
   client:
      serviceUrl:
         defaultZone: http://eureka-server:8761/eureka/