version: '3'
services:
   eureka-server:
      hostname: eureka-server
      build:
         context: discoveryServer
         dockerfile: Dockerfile
      image: studenteurekaserver
      ports: 
        - 8761:8761
      container_name: eureka-server
      restart: on-failure
      networks:
        - student-network
      depends_on:
        - kafka-server
        - mysql-server
   zuul-apigateway-server:
      build:
         context: zuulApiGateway
         dockerfile: Dockerfile
      image: studentapigateway
      ports:
        - 8762:8762
      container_name: zuul-apigateway-server
      restart: on-failure
      networks:
        - student-network
      depends_on:
        - eureka-server
   student-service:
      build:
         context: studentService
         dockerfile: Dockerfile
      image: studentservice
      ports:
        - 8082:8082
      container_name: student-service
      restart: on-failure
      networks:
        - student-network
      depends_on:
        - eureka-server
   fees-service:
      build:
         context: feesService
         dockerfile: Dockerfile
      image: feeservice
      ports:
        - 8084:8084
      container_name: fees-service
      restart: on-failure
      networks:
        - student-network
      depends_on:
        - eureka-server
   exams-service:
      build:
         context: examsService
         dockerfile: Dockerfile
      image: examservive
      ports:
        - 8083:8083
      container_name: exams-service
      restart: on-failure
      networks:
        - student-network
      depends_on:
        - eureka-server
   mysql-server:
      image: mysql/mysql-server:8.0
      restart: always
      container_name: mysql-server
      environment:
         MYSQL_ROOT_PASSWORD: rootpw
         MYSQL_ROOT_HOST: '%'
      ports:
        - 3307:3306
      volumes:
        - mysql_db_data_container:/var/lib/mysql
      networks:
        - student-network
   kafka-server:
      image: wurstmeister/kafka:latest
      container_name: kafka-server
      ports:
        - 9092:9092
      environment:
        - KAFKA_ADVERTISED_HOST_NAME=kafka-server
        - KAFKA_ADVERTISED_PORT=9092
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      depends_on:
        - zookeeper
      networks:
        - student-network
   zookeeper:
      image: wurstmeister/zookeeper:latest
      container_name: zookeeper
      ports:
        - 2181:2181
      environment:
        - KAFKA_ADVERTISED_HOST_NAME=zookeeper
      networks:
        - student-network
volumes:
   mysql_db_data_container: null
networks:
   student-network:
      driver: bridge